# Meta Data for SEO

## Homepage
title = "Notion Charts"
titleSeparator = "-"
titleAddition = "Create charts in Notion without ever leaving"
description = "Notion Charts is the simplest way to add charting capabilities to your Notiont Workspaces and Databases"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "www.notion-charts.app"
titleHome = "Notion Charts"

## Twitter Cards
# twitterSite = "@getdoks"
# twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
# schemaType = "Organization"
# schemaName = "Doks"
# schemaAuthor = "Henk Verlinde"
# schemaAuthorTwitter = "https://twitter.com/henkverlinde"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
# schemaAuthorGitHub = "https://github.com/h-enk"
# schemaLocale = "en-US"
# schemaLogo = "logo-doks.png"
# schemaLogoWidth = 512
# schemaLogoHeight = 512
# schemaImage = "doks.png"
# schemaImageWidth = 1280
# schemaImageHeight = 640
# schemaTwitter = "https://twitter.com/getdoks"
# schemaLinkedIn = ""
# schemaGitHub = "https://github.com/h-enk/doks"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "notion-charts-banner.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Notion Charts"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"
alertText = "Notion Charts is now in Beta!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/michmich112/notion-charts-web"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
